name: Invoice Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploying invoice app
      env:
        HEROKU_API_KEY: 231e3ae7-32d2-48fd-bc10-526f1dc4367c
        APP_NAME: olla-invoice
      run: |
        docker build -t olla-invoice .
        docker tag olla-invoice registry.heroku.com
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
      
       
